# Generated by Django 5.2.8 on 2025-11-24 20:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação')),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Dados Manual'), (2, 'Dados de API'), (3, 'Dados Externo')], default=1, null=True, verbose_name='Origem dos Dados')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTag',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Modificação')),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Dados Manual'), (2, 'Dados de API'), (3, 'Dados Externo')], default=1, null=True, verbose_name='Origem dos Dados')),
                ('nome', models.CharField(db_index=True, max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tag',
                'verbose_name_plural': 'historical Tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
