
ORIGEM_DADOS_MANUAL = 1
ORIGEM_DADOS_API = 2
ORIGEM_DADOS_EXTERNO = 3

C_TIPO_ORIGEM_DADOS = [
    (ORIGEM_DADOS_MANUAL, 'Dados Manual'),
    (ORIGEM_DADOS_API, 'Dados de API'),
    (ORIGEM_DADOS_EXTERNO, 'Dados Externo')
]

