# Generated by Django 5.2.8 on 2025-11-24 21:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('criado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de Modificação')),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Dados Manual'), (2, 'Dados de API'), (3, 'Dados Externo')], default=1, null=True, verbose_name='Origem dos Dados')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Post',
                'verbose_name_plural': 'historical Posts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Modificação')),
                ('origem_dados', models.IntegerField(blank=True, choices=[(1, 'Dados Manual'), (2, 'Dados de API'), (3, 'Dados Externo')], default=1, null=True, verbose_name='Origem dos Dados')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tags', models.ManyToManyField(related_name='posts', to='tags.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-modificado'],
            },
        ),
    ]
