# Generated by Django 5.2.8 on 2025-11-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='status',
            field=models.IntegerField(choices=[(1, 'Rascunho'), (2, 'Publicado')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Rascunho'), (2, 'Publicado')], default=1, verbose_name='Status'),
        ),
    ]
