# Generated by Django 5.2.8 on 2025-12-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_historicalpost_status_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
